### ISSUE TITLE
Error BPXM023I (LBDYCK) SCRT: Failed to register - Code 8 under OMVS

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gumport#2]
This error occurs when invoking `gum -v` under OMVS but it works under SSH.

**Comment by ccw-1** [comment]
I am not sure why SCRT doesn't work under OMVS,  but you can suppress the message with `PROFILE NOWTPMSG` in TSO.

**Comment by lbdyck** [comment]
very true but in this case the user is under OMVS at this point and they may want the WTPMSG enabled by default for other things.

**Comment by lbdyck** [comment]
fixed with 0.13.0
